version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run: ./.scripts/install-deps.sh

workflows:
  version: 2
  master-release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
