version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8

    environment:
      METEOR_VERSION: 1.8.1

    steps:
      - checkout
      - restore_cache:
          key: v1-build-cache
      - run: ./.scripts/install-deps.sh
      - run: ./.scripts/install-meteor.sh
      - save_cache:
          key: v1-build-cache

workflows:
  version: 2
  master-release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
