name: Node CI

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build docker image
      run: |
        ./build-docker.sh
      env:
        CI: true
        METEOR_VERSION: 1.8.1
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
