name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        ./build-meteor.sh
      env:
        CI: true
        METEOR_VERSION: 1.8.1
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
