name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      env:
        CI: true
        METEOR_VERSION: 1.8.1
        BUNDLE_DIR: ${{ env.home }}
        BUILD_FLAGS: --architecture os.linux.x86_64  --allow-superuser --server-only
      run: |
        echo ${HOME}
        echo ${BUNDLE_DIR}
